version: '3.9'
services:
  dnsrobocert:
    image: adferrand/dnsrobocert:3.15.0
    container_name: 'dnsrobocert'
    volumes:
      - ${DOCKER_MOUNT_DIR}/dnsrobocert/config:/etc/dnsrobocert
      - ${DOCKER_MOUNT_DIR}/letsencrypt:/etc/letsencrypt
